services:
  nginx:
    image: nginx:latest
    container_name: nginx-shortlink
    ports:
      - "18080:80"
    volumes:
      - ~/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - linkflow-net
    depends_on:
      shortlink1:
        condition: service_started
      shortlink2:
        condition: service_started
      shortlink3:
        condition: service_started

  shortlink1:
    image: short-link-app:3.0
    container_name: shortlink1
    environment:
      SPRING_PROFILES_ACTIVE: docker
      WORKER_ID: 1
      SERVER_PORT: 8080
      DUBBO_HOST: shortlink1
    networks:
      - linkflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  shortlink2:
    image: short-link-app:3.0
    container_name: shortlink2
    environment:
      SPRING_PROFILES_ACTIVE: docker
      WORKER_ID: 2
      SERVER_PORT: 8081
      DUBBO_HOST: shortlink2
    networks:
      - linkflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  shortlink3:
    image: short-link-app:3.0
    container_name: shortlink3
    environment:
      SPRING_PROFILES_ACTIVE: docker
      WORKER_ID: 3
      SERVER_PORT: 8082
      DUBBO_HOST: shortlink3
    networks:
      - linkflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  linkflow-net:
    external: true
