version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://100.112.194.13:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nginx:
    image: nginx:latest
    container_name: nginx-shortlink
    ports:
      - "80:80"
    volumes:
      - ~/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

  shortlink1:
    image: short-link-app:3.0
    container_name: shortlink1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WORKER_ID=1
      - SERVER_PORT=8080

  shortlink2:
    image: short-link-app:3.0
    container_name: shortlink2
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WORKER_ID=2
      - SERVER_PORT=8081

  shortlink3:
    image: short-link-app:3.0
    container_name: shortlink3
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WORKER_ID=3
      - SERVER_PORT=8082