spring.application.name=short-link

snowflake.worker-id=1

hashids.salt=short-link-salt
hashids.min-length=6

kafka.topic.click=click-topic
kafka.consumer.group-id=short-link-group

Redis.keys.clickSet=click:keys
Redis.keys.prefix.click=click:
