spring.application.name=short-link

hashids.salt=short-link-salt
hashids.min-length=6

kafka.topic.click=click-topic
kafka.topic.createShortLink=create-short-link-topic
kafka.consumer.group-id=short-link-group

Redis.keys.clickSet=click:keys
Redis.keys.prefix.click=click:
